my_list = [8, 2, 3, -3, 'Ana are mere', [1, 2, 3]]
# my_list.append(8)
# my_list.append(2)
# my_list.append(-2)
# my_list.append(10)
# my_list.append("Ana are mere")
# print(my_list[0])
# print(len(my_list))
# print(my_list[5])
# print(my_list[6])
# print(my_list[-1])
# print(my_list[2:])
# print(my_list[2:5])
# print(my_list[:3])
# print(my_list[8:9])
